all:
	gcc assessment.c bmpReader.c -Wall -g -O2 -lm -o run
	gcc entropyCoding.c -Wall -g -O2 -lm -o coding
	gcc huffmanTreeConstructor.c -Wall -g -O2 -lm -o tree
	gcc byteReader.c -Wall -g -O2 -lm -o byte
clean:
	rm run
	rm coding
	rm tree
	rm byte